version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["deps","github-actions"]
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["deps","composer"]
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "laravel/framework"
        update-types: ["version-update:semver-major"]
