name: Packagist Auto Update

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    if: github.repository_owner != 'dependabot[bot]'
    steps:
      - name: Notify Packagist
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: |
          if [ -z "$PACKAGIST_USERNAME" ] || [ -z "$PACKAGIST_TOKEN" ]; then
            echo "Packagist credentials not set; skipping." && exit 0
          fi
          echo "Triggering Packagist update for repo ${GITHUB_REPOSITORY}"
          curl -s -o /dev/null -w "%{http_code}\n" \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{"repository":{"url":"https://github.com/'"${GITHUB_REPOSITORY}"'"}}' \
            "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_TOKEN}" | grep -q '^2' || echo "Packagist update call returned non-2xx status" 
